### PR TITLE
LAW ENFORCEMENT INTERCOURSE

### PR DESCRIPTION
**Pull request by dequis**
LAW ENFORCEMENT INTERCOURSE

### CODE REVIEW

**Comment by qpfiffer** [comment]
@dx can you turn this into a strikethrough instead, to preserve content?

**Comment by lykkin** [comment]
no, this is fine :+1:

**Comment by qpfiffer** [comment]
@dequis, even

**Comment by dequis** [comment]
no

**Comment by qpfiffer** [comment]
image

**Comment by dequis** [comment]
Coverage Status

Coverage increased (+4.81%) to 96.05% when pulling **3d4f6322af91effa3e49705a6d1b3d96de2b7ab5 on dequis:LAW-ENFORCEMENT-INTERCOURSE** into **818ce816f3f6b578acfcbd895d6e04220987d536 on qpfiffer:master**.

**Comment by qpfiffer** [comment]
Oh, well if the coverage increased, why not? :package: :finnadie:

**Pull request merged**
