### PR TITLE
Lua Masterclass

### PR DESCRIPTION
**Pull request by qpfiffer**
Rewrites the entire Lua stack to be integrated via the C FFI, instead of using subprocess calls.

Still todo:
* Rewrite the rest of the views
* Make sure the `VERSION` is correct in the Makefile
* Make sure the Gentoo package builds correctly
* Check for memory leaks

### CODE REVIEW

**Comment by lykkin** [comment]
yeah but what about the ruby support?

**Comment by dequis** [comment]
:package:

**Comment by cblgh** [comment]
📦

**Comment by Dman757** [comment]
I came here to recycle this cardboard pls break down your 📦 or the garbage won't accept it.

**Comment by cblgh** [comment]
🟧🟧🟧🟧🔶🔶🔶🔶

**Comment by lykkin** [comment]
```haskell
Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;

Then took the other, as just as fair,
And having perhaps the better claim,
Because it was grassy and wanted wear;
Though as for that the passing there
Had worn them really about the same,

And both that morning equally lay
In leaves no step had trodden black.
Oh, I kept the first for another day!
Yet knowing how way leads on to way,
I doubted if I should ever come back.

I shall be telling this with a sigh
Somewhere ages and ages hence:
Two roads diverged in a wood, and I—
I took the one less traveled by,
And that has made all the difference.
```

**Pull request merged**
